FROM openjdk:11
MAINTAINER  @engkaranja
VOLUME /tmp
EXPOSE 8000                  
COPY country-phone-number-0.0.1-SNAPSHOT.jar country-phone-number-0.0.1-SNAPSHOT.jar 
ENTRYPOINT ["java","-jar","/country-phone-number-0.0.1-SNAPSHOT.jar"] 